all:
	javadoc -d docs/manual main/java/peer/*
	javac -d . main/java/peer/*
clean:
	sudo rm -r ./tests/* ./docs/manual/* ./main/java/*/*~ ./main/java/*/*.class ./main/java/*/#*# ./*~ ./*/*~ ../topologies/topo/*
